# Generated by Django 5.2.5 on 2025-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.TextField()),
                ('short_story', models.TextField()),
                ('character_description', models.TextField()),
                ('background_description', models.TextField()),
                ('character_image_prompt', models.TextField()),
                ('background_image_prompt', models.TextField()),
                ('char_img_path', models.CharField(max_length=255)),
                ('bg_img_path', models.CharField(max_length=255)),
                ('combined_img_path', models.CharField(max_length=255)),
            ],
        ),
    ]
